export const CREATE_CHAT_START = 'CREATE_CHAT_START';
export const CREATE_CHAT_SUCCESS = 'CREATE_CHAT_SUCCESS';
export const CREATE_CHAT_FAIL = 'CREATE_CHAT_FAIL';

export const GET_CHAT_START = 'GET_CHAT_START';
export const GET_CHAT_SUCCESS = 'GET_CHAT_SUCCESS';
export const GET_CHAT_FAIL = 'GET_CHAT_FAIL';

export const GET_MESSAGES_START = 'GET_MESSAGES_START';
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';
export const GET_MESSAGES_FAIL = 'GET_MESSAGES_FAIL';

export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';
